name: Deploy

on:
  push:
    branches:
      - main
      - test

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
      - name: Create .env file
        run: |
          echo "INSTAGRAM_CLIENT_ID=${{ secrets.INSTAGRAM_CLIENT_ID }}" >> .env
          echo "INSTAGRAM_CLIENT_SECRET=${{ secrets.INSTAGRAM_CLIENT_SECRET }}" >> .env
          echo "INSTAGRAM_REDIRECT_URI=${{ secrets.INSTAGRAM_REDIRECT_URI }}" >> .env
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> .env

  report-build-status:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Report build status
        run: echo "Build completed successfully."

  deploy:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
