name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Inject env vars into JS
        run: |
          sed -i "s|__INSTAGRAM_CLIENT_ID__|${{ secrets.INSTAGRAM_CLIENT_ID }}|g" public/fb-login.js
          sed -i "s|__INSTAGRAM_CLIENT_SECRET__|${{ secrets.INSTAGRAM_CLIENT_SECRET }}|g" public/fb-login.js
          sed -i "s|__INSTAGRAM_REDIRECT_URI__|${{ secrets.INSTAGRAM_REDIRECT_URI }}|g" public/fb-login.js

      - name: Build
        run: npm run build

  report-build-status:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Report build status
        run: echo "Build completed successfully."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
